# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor.shape, random_tensor.dtype,random_tensor


(torch.Size([7, 7]),
 torch.float32,
 tensor([[0.8446, 0.1857, 0.8391, 0.9099, 0.7720, 0.7121, 0.0578],
         [0.7941, 0.3375, 0.0937, 0.5511, 0.4991, 0.4359, 0.2438],
         [0.4308, 0.7960, 0.7046, 0.9721, 0.7898, 0.1706, 0.7269],
         [0.3330, 0.7560, 0.2746, 0.3538, 0.3104, 0.2644, 0.5743],
         [0.4264, 0.7314, 0.8714, 0.8825, 0.0783, 0.4920, 0.7568],
         [0.2475, 0.3259, 0.4933, 0.3467, 0.8444, 0.3229, 0.6916],
         [0.0193, 0.5045, 0.5864, 0.2232, 0.1079, 0.4146, 0.8447]]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
random_tensor2 = torch.randn(size=(1, 7))

# Perform matrix multiplication 
res = random_tensor2 @ random_tensor
res,res.shape

(tensor([[1.2622, 0.8515, 0.6671, 1.2436, 0.3286, 0.8724, 0.4324]]),
 torch.Size([1, 7]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
random_seed = 0

# Create two random tensors
random_tensor_1 = torch.rand(7, 7)
random_tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(random_tensor_1, random_tensor_2.T)


tensor([[1.0344],
        [0.8223],
        [0.6167],
        [0.6359],
        [1.3726],
        [0.8537],
        [1.1759]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
import torch.share


random_seed = 7

# Create random tensor
torch.manual_seed(random_seed)
random_tensor_1 = torch.rand(1,1,1,10)
random_tensor_1.shape,random_tensor_1

# Remove single dimensions
random_tensor_2 = random_tensor_1.squeeze()
random_tensor_2.shape,random_tensor_2


# Print out tensors and their shapes
print(f"Random Tensor 1:\n{random_tensor_1}\n")
print(f"Random Tensor 2:\n{random_tensor_2}\n")
print(f"Random Tensor 1 Shape: {random_tensor_1.shape}")
print(f"Random Tensor 2 Shape: {random_tensor_2.shape}")


Random Tensor 1:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

Random Tensor 2:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

Random Tensor 1 Shape: torch.Size([1, 1, 1, 10])
Random Tensor 2 Shape: torch.Size([10])
